{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rtdb.serviceAccountName" . }}
  labels:
{{ include "rtdb.labels" . | indent 4 }}
{{- end -}}
