#!/bin/bash

#if [ ! -f "${OPENSHIFT_DATA_DIR}le" ];
#then
	#wget https://github.com/MarkLC/le_openshift/raw/master/le -O ${OPENSHIFT_DATA_DIR}le --no-check-certificate -q
	
#	chmod +x ${OPENSHIFT_DATA_DIR}le
#fi

chmod +x ${OPENSHIFT_REPO_DIR}logentries/le

if [ ! -f "${OPENSHIFT_DATA_DIR}config" ];
then
	${OPENSHIFT_REPO_DIR}logentries/le register --hostname=${OPENSHIFT_APP_NAME}
fi

#.${OPENSHIFT_DATA_DIR}/le monitor
