kind: pipeline
name: build
type: kubernetes

# test       
steps:
- name: test
  image: node:17
  commands:
  - npm install
  - npm test
- name: build-rtdb
  image: plugins/kaniko:1.4.1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: chicagozer/rtdb
    dockerfile: Dockerfile
    tags:
      - kaniko

