kind: pipeline
name: build

# test   
steps:
- name: build-rtdb
#  image: plugins/kaniko:1.3.1
  image: plugins/kaniko:1.4.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: chicagozer/rtdb
    dockerfile: Dockerfile
    tags:
      - kaniko

