kind: pipeline
type: docker
name: default

steps:
#- name: test   
#  image: node
#  commands:
#    - npm install 
- name: docker  
  image: banzaicloud/drone-kaniko
  settings:
    username: chicagozer
    password:
      from_secret: docker_password
    repo: chicagozer/rtdb
    tags:
      - harness
