# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: "rtdb"
    IMAGE_TAG: "kaniko"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing Mocha...
      - export
  pre_build:
    commands:
      - AWS_ACCOUNT_ID=${CODEBUILD_BUILD_ARN} && IFS=':' && set -- $AWS_ACCOUNT_ID && AWS_ACCOUNT_ID=$5
      - echo Installing source NPM dependencies...
      - npm install
#      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
       - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/d5y7k0n6
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm test
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG public.ecr.aws/d5y7k0n6/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/d5y7k0n6/$IMAGE_REPO_NAME:$IMAGE_TAG
